# Generated by Django 4.0.3 on 2022-08-26 00:11

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_myuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cpf',
            field=cpf_field.models.CPFField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
