# Generated by Django 4.0.3 on 2022-08-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_myuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='donator',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blood_bank.myuser'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blood_bank.myuser'),
        ),
    ]
