# Generated by Django 4.0.3 on 2022-08-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_donator_is_active_donator_user_nurse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.myuser'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.myuser'),
        ),
    ]
