# Generated by Django 4.0.3 on 2022-08-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_alter_donator_user_alter_nurse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
