# Generated by Django 4.0.3 on 2022-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0006_alter_myuser_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.AddField(
            model_name='donator',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
