# Generated by Django 4.0.3 on 2022-09-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0007_remove_myuser_cpf_remove_myuser_name_donator_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='name',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donator',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
