# Generated by Django 4.0.3 on 2022-09-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0009_nurse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donator',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(default=None, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
    ]
