# Generated by Django 4.0.3 on 2022-09-01 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0010_remove_donator_birth_date_myuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 20, 44, 6, 123402), verbose_name='Data de Nascimento'),
        ),
    ]
