# Generated by Django 4.0.3 on 2022-09-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0011_alter_myuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
